// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeamBoardApiServer.Models;

namespace TeamBoardApiServer.Migrations
{
    [DbContext(typeof(TeamBoardApiServerContext))]
    [Migration("20190412215431_Instantiate")]
    partial class Instantiate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TeamBoardApiServer.Models.Board", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<Guid?>("OwnerId");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("TeamBoardApiServer.Models.BoardToUser", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<Guid>("BoardId");

                    b.HasKey("UserId", "BoardId");

                    b.HasIndex("BoardId");

                    b.ToTable("BoardToUser");
                });

            modelBuilder.Entity("TeamBoardApiServer.Models.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("BoardId");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("TeamBoardApiServer.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Firstname");

                    b.Property<string>("Lastname");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TeamBoardApiServer.Models.Board", b =>
                {
                    b.HasOne("TeamBoardApiServer.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");
                });

            modelBuilder.Entity("TeamBoardApiServer.Models.BoardToUser", b =>
                {
                    b.HasOne("TeamBoardApiServer.Models.Board", "Board")
                        .WithMany("Members")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TeamBoardApiServer.Models.User", "User")
                        .WithMany("Boards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("TeamBoardApiServer.Models.Item", b =>
                {
                    b.HasOne("TeamBoardApiServer.Models.Board")
                        .WithMany("Items")
                        .HasForeignKey("BoardId");
                });
#pragma warning restore 612, 618
        }
    }
}
